CREATE SCHEMA notes;

CREATE TABLE notes (
	id		BIGSERIAL	PRIMARY KEY,
	title		VARCHAR(60)	NOT NULL,
	body		TEXT		NOT NULL,
	tags		TEXT[],
	created_at		TIMESTAMP	NOT NULL DEFAULT now(),
	updated_at		TIMESTAMP	NOT NULL DEFAULT now()
);
